output_dir: ./output

versions:
  - SNAPSHOT
  - 19.07.3

json_url: https://images.aparcar.org/rebuild
base_url: https://downloads.cdn.openwrt.org

repos:
  - base
  - luci
  - packages
  - routing
  - telephony

targets:
  apm821xx/nand:
    arch: powerpc_464fp
  apm821xx/sata:
    arch: powerpc_464fp
  arc770/generic:
    arch: arc_arc700
  archs38/generic:
    arch: arc_archs
  armvirt/32:
    arch: arm_cortex-a15_neon-vfpv4
  armvirt/64:
    arch: aarch64_generic
  at91/sam9x:
    arch: arm_arm926ej-s
  at91/sama5:
    arch: arm_cortex-a5_vfpv4
  ath25/generic:
    arch: mips_mips32
  ath79/generic:
    arch: mips_24kc
  ath79/mikrotik:
    arch: mips_24kc
  ath79/nand:
    arch: mips_24kc
  ath79/tiny:
    arch: mips_24kc
  bcm27xx/bcm2708:
    arch: arm_arm1176jzf-s_vfp
  bcm27xx/bcm2709:
    arch: arm_cortex-a7_neon-vfpv4
  bcm27xx/bcm2710:
    arch: aarch64_cortex-a53
  bcm27xx/bcm2711:
    arch: aarch64_cortex-a72
  bcm47xx/generic:
    arch: mipsel_mips32
  bcm47xx/legacy:
    arch: mipsel_mips32
  bcm47xx/mips74k:
    arch: mipsel_74kc
  bcm53xx/generic:
    arch: arm_cortex-a9
  bcm63xx/generic:
    arch: mips_mips32
  bcm63xx/smp:
    arch: mips_mips32
  cns3xxx/generic:
    arch: arm_mpcore_vfp
  gemini/generic:
    arch: arm_fa526
  imx6/generic:
    arch: arm_cortex-a9_neon
  ipq40xx/generic:
    arch: arm_cortex-a7_neon-vfpv4
  ipq806x/generic:
    arch: arm_cortex-a15_neon-vfpv4
  kirkwood/generic:
    arch: arm_xscale
  lantiq/ase:
    arch: mips_mips32
  lantiq/falcon:
    arch: mips_24kc
  lantiq/xrx200:
    arch: mips_24kc
  lantiq/xway:
    arch: mips_24kc
  lantiq/xway_legacy:
    arch: mips_24kc
  layerscape/armv7:
    arch: arm_cortex-a7_neon-vfpv4
  layerscape/armv8_64b:
    arch: aarch64_generic
  malta/be:
    arch: mips_24kc
  mediatek/mt7622:
    arch: aarch64_cortex-a53
  mediatek/mt7623:
    arch: arm_cortex-a7_neon-vfpv4
  mediatek/mt7629:
    arch: arm_cortex-a7
  mpc85xx/generic:
    arch: powerpc_8540
  mpc85xx/p1010:
    arch: powerpc_8540
  mpc85xx/p1020:
    arch: powerpc_8540
  mpc85xx/p2020:
    arch: powerpc_8540
  mvebu/cortexa53:
    arch: aarch64_cortex-a53
  mvebu/cortexa72:
    arch: aarch64_cortex-a72
  mvebu/cortexa9:
    arch: arm_cortex-a9_vfpv3
  mxs/generic:
    arch: arm_arm926ej-s
  octeon/generic:
    arch: mips64_octeonplus
  octeontx/generic:
    arch: aarch64_generic
  omap/generic:
    arch: arm_cortex-a8_vfpv3
  oxnas/ox820:
    arch: arm_mpcore
  pistachio/generic:
    arch: mipsel_24kc_24kf
  ramips/mt7620:
    arch: mipsel_24kc
  ramips/mt7621:
    arch: mipsel_24kc
  ramips/mt76x8:
    arch: mipsel_24kc
  ramips/rt288x:
    arch: mipsel_24kc
  ramips/rt305x:
    arch: mipsel_24kc
  ramips/rt3883:
    arch: mipsel_74kc
  rb532/generic:
    arch: mipsel_mips32
  rockchip/armv8:
    arch: aarch64_generic
  samsung/s5pv210:
    arch: arm_cortex-a8_neon
  sunxi/cortexa53:
    arch: aarch64_cortex-a53
  sunxi/cortexa7:
    arch: arm_cortex-a7_neon-vfpv4
  sunxi/cortexa8:
    arch: arm_cortex-a8_vfpv3
  tegra/generic:
    arch: arm_cortex-a9_vfpv3
  x86/64:
    arch: x86_64
  x86/generic:
    arch: i386_pentium4
  x86/geode:
    arch: i386_pentium
  x86/legacy:
    arch: i386_pentium
  zynq/generic:
    arch: arm_cortex-a9_neon
